; Listing generated by Microsoft (R) Optimizing Compiler Version 19.20.27508.1 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\benie.DESKTOP-K69F1U6\AppData\Local\Temp\.NETFramework,Version=v4.7.2.AssemblyAttributes.cpp"
